/**
 * SECURITY: Secure Supabase Client Configuration
 * Uses environment variables and implements security best practices
 * This file is automatically generated but enhanced with security measures.
 */

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/lib/environment';
import { secureLog, secureError } from '@/lib/validation';
import { securityMonitor } from '@/lib/security-middleware';

/**
 * SECURITY: Validate required environment variables
 * Prevents runtime errors from missing configuration
 */
if (!env.VITE_SUPABASE_URL || !env.VITE_SUPABASE_PUBLISHABLE_KEY) {
  const error = 'Missing required Supabase configuration';
  secureError(error);
  throw new Error(error);
}

/**
 * SECURITY & PERFORMANCE: Enhanced Supabase client configuration
 */
export const supabase = createClient<Database>(
  env.VITE_SUPABASE_URL,
  env.VITE_SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      // SECURITY: Secure session storage
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      
      // SECURITY: Enhanced auth configuration
      detectSessionInUrl: true,
      flowType: 'pkce', // Use PKCE flow for better security and mobile compatibility
      
      // SECURITY: Auto logout on suspicious activity
      debug: false, // Disable debug logs in production
    },
    
    // PERFORMANCE: Connection configuration
    db: {
      schema: 'public',
    },
    
    // SECURITY: Request configuration
    global: {
      headers: {
        'X-Client-Info': 'worksite-sync-app',
      },
    },
    
    // PERFORMANCE: Real-time configuration
    realtime: {
      params: {
        eventsPerSecond: 10, // Rate limit real-time events
      },
    },
  }
);

/**
 * SECURITY: Monitor authentication events
 * Logs security-relevant authentication events for monitoring
 */
supabase.auth.onAuthStateChange((event, session) => {
  const eventMap = {
    'SIGNED_IN': 'authentication',
    'SIGNED_OUT': 'authentication',
    'TOKEN_REFRESHED': 'authentication',
    'USER_UPDATED': 'authentication',
    'PASSWORD_RECOVERY': 'authentication',
  } as const;
  
  const eventType = eventMap[event as keyof typeof eventMap] || 'suspicious_activity';
  
  securityMonitor.logSecurityEvent({
    type: eventType,
    severity: event === 'SIGNED_IN' ? 'low' : 'medium',
    message: `Auth event: ${event}`,
    metadata: {
      event,
      userId: session?.user?.id,
      email: session?.user?.email,
      timestamp: new Date().toISOString()
    }
  });
  
  // Log successful authentication events
  if (event === 'SIGNED_IN') {
    secureLog('User authenticated successfully', {
      userId: session?.user?.id,
      email: session?.user?.email
    });
  }
});

/**
 * SECURITY: Enhanced error handling for Supabase operations
 * Wraps Supabase responses to provide consistent error handling
 */
export const handleSupabaseResponse = <T>(
  operation: Promise<{ data: T; error: any }>,
  context?: string
) => {
  return operation.then(({ data, error }) => {
    if (error) {
      securityMonitor.logSecurityEvent({
        type: 'suspicious_activity',
        severity: 'medium',
        message: `Supabase operation failed: ${context || 'unknown'}`,
        metadata: {
          error: error.message,
          code: error.code,
          context
        }
      });
      
      secureError('Supabase operation failed', { error, context });
    } else if (context) {
      secureLog('Supabase operation successful', { context });
    }
    
    return { data, error };
  });
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";