// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kejblmetyrsehzvrxgmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlamJsbWV0eXJzZWh6dnJ4Z210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTI1NTIsImV4cCI6MjA2OTk2ODU1Mn0.4CxLNIJtyjWDgoxNzKOwz1LiKnuRHkVubort9fiFxac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});